[versions]
spring-boot = "3.2.0"
postgresql = "42.6.0"
caffeine = "3.1.8"

[libraries]
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc", version.ref = "spring-boot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

[bundles]
persistence = ["spring-boot-starter-data-jdbc", "postgresql"]
caching = ["spring-boot-starter-cache", "caffeine"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
io-spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.4" }