spring:
  application:
    name: gateway
  liquibase:
    change-log: classpath:db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    rest:
      uris: http://${localhost}:${9200}

minio:
  endpoint: http://localhost:8000
  accessKey: minioadmin
  secretKey: minioadmin123

app:
  s3:
    photo-bucket: photos