spring:
  application:
    name: gateway

  elasticsearch:
    rest:
      uris: http://${localhost}:${9200}

minio:
  endpoint: http://localhost:8000
  accessKey: minioadmin
  secretKey: minioadmin123

app:
  s3:
    photo-bucket: photos